name: iOS CI (Build & Test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build
        run: |
          xcodebuild clean build \
            -project SwiftCIExample.xcodeproj \
            -scheme SwiftCIExample \
            -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Run Tests
        run: |
          xcodebuild test \
            -project SwiftCIExample.xcodeproj \
            -scheme SwiftCIExample \
            -destination 'platform=iOS Simulator,name=iPhone 15'
