name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --project-directory=.

    - name: Build
      run: |
        xcodebuild clean build \
        -workspace YourProject.xcworkspace \
        -scheme YourSchemeName \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15'

    - name: Run Tests
      run: |
        xcodebuild test \
        -workspace YourProject.xcworkspace \
        -scheme YourSchemeName \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15'
